{% set name = "vtki" %}
{% set version = "0.18.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eab6cc58ce1125eea7034bf6e8081ffb518e5eb0ad5214758bbec73872cedb4c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - numpy
    - imageio
    - appdirs
    - vtk <=8.1.2
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - imageio
    - appdirs
    - vtk <=8.1.2

test:
  imports:
    - vtki

about:
  home: https://github.com/vtkiorg/vtki
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Streamlined Python Interface for the Visualization Toolkit'

  description: |
    vtki is a VTK helper module that takes a different approach on interfacing with VTK through NumPy and direct array access. This module simplifies mesh creation and plotting by adding functionality to existing VTK objects. This module can be used for scientific plotting for presentations and research papers as well as a supporting module for other mesh dependent Python modules.
  doc_url: http://docs.vtki.org/en/latest/
  dev_url: https://github.com/vtkiorg/vtki

extra:
  recipe-maintainers:
    - banesullivan
    - hadim
