travis:
  secure:
    BINSTAR_TOKEN: h4JBcaTOjj2hNN0HPcFmUvf8idFEdaJ9n52/X6bt7QFp5z46MeImvOvPOK2D4azYrrrOEls+nLr6xntyRl/9AjxH5FPASOynjTQHFqLuFJbguX/ydPksKhZg5NHE/WSnByb5LLRIW7bq06Gtqz/E1FIjBVoppB4BGKJyNBRE0P99MtKE0kWfi9RdwgM1Ipp59rtEd44Hvc6GcInXq86QZZPAOIke5bGpfESJnlhfwmp+2JK5zEv6e3/MwwYqzO2bjK50MZLOGDaE9+igT6IIAfuKv3yjOfxlVtgE3yiVLlWgN1esjkbChhcmQA0WeidBaRjNRsbTFctFwGSWi/SypD3ebnKHz9lkXCQ5YHz9c3/J8Rt5LU+YyORN5w44VEUviopE0OPbFCoBCcnbPj9ySTTTMusuuMtOtyLizfML+3aas12dSZWHe/R3XHa0CutNU9wgitqTCTwekizjKXzOBanNNuwGAdcj1xPC+zftqGD3h1qEMNbGv6trSD47ijbS39rnY6WAl2n2kREzXTgnwz7mDZOOclWcc9nlAjR4ByGHkpz2MNlWKaOcRWBpga2L+L2k4T7AC43JWzcHTWiDyetKOK13nhXlbOKf9yTGQXH9trrBWlAZKYWPlPYB3Jlj5+ZqVKprBUM3LbxJvNEFVGy6qE2F2iUG+VVnerB8/ac=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
